### ISSUE TITLE
Test new colours on low-contrast monitor

### ISSUE THREAD

**Issue by sampling** [barnardos/design-system#18]
_As a user of the design system
I want to ensure that not only are the colours accessible, but they are also robust and stand up to different monitor types including those with low contrast
So that the Barnardo's brand look and feel holds up and maintains consistency_

## Acceptance Criteria

- [x] Testing the newly chosen accessible colour palette on low contrast monitors
- [x] Tweaking the colours if needed, ensuring they stay accessible and on brand

**Comment by tosbourn** [comment]
It it helps here is the last year's worth of data on screen colours on the main website excluding internal traffic.

24-bit much higher than I expected.

<img width="1210" alt="screen shot 2018-02-19 at 13 50 37" src="https://user-images.githubusercontent.com/456902/36380990-1edafcca-157c-11e8-9d85-a6d9d3447cc1.png">

Also browser by OS (because I know OS can have a big impact on what colours make it to the screen)

<img width="1208" alt="screen shot 2018-02-19 at 13 51 19" src="https://user-images.githubusercontent.com/456902/36381091-67252604-157c-11e8-9d91-d27ede7c02ce.png">

**Comment by kelliewellingtons** [comment]
Tests have been done with high and low contrast settings.

Colours can still be clearly differentiated, and feel like a family and on brand.

Consider this ticket to be completed.

![photo 20-02-2018 13 16 18](https://user-images.githubusercontent.com/6122118/36426146-1205758c-1641-11e8-83dc-d38af1254c8a.jpg)
![photo 20-02-2018 13 16 57](https://user-images.githubusercontent.com/6122118/36426150-1672d47a-1641-11e8-8065-f3a806aed59f.jpg)
