### ISSUE TITLE
Review blog post

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#215]
A blog post has been drafted and is ready for review

### Links and resources

Draft blog post:
https://docs.google.com/document/d/10U7ZIDn_YsyvgL63wVZvNdakyR1i1dWB5U8DkPlmyuI/edit#

### Acceptance criteria

- [x] Read draft
- [x] Make suggestions for changes (or approve)
- [x] Create relevant follow up issues

**Comment by kelliedesigner** [comment]
Could we have a comment here with an update on the review of the draft?

**Comment by kelliedesigner** [comment]
@olliewright Could we have a comment here with an update on the review of the draft?

**Comment by sl33p** [comment]
Sorry about the delay in replying to this.

I think the content of the post is absolutely right, the intro, what's working well and next steps sections are right for this first post about the design system, and it makes sense to make room to follow up with more in-depth articles about e.g. the advantage of working directly in code, or the advantages of a cross-disciplinary design team (of two).

What I would like to see in this post is an expansion of each of the points mentioned. As it is the post reads like an introduction, or an abstract. The current word count is 142, short is sweet, and people don't trawl through blog posts that waffle on. However, this intro (first post!) should set out the stall a little bit more for all the awesome stuff we have in the pipeline. I really think it would make for a much more solid post if each of the three sections had an additional couple of paragraphs, answering some of the following questions: 

- **save time by not reinventing the wheel**  
What does this mean? How can I save time? Give an example.
- **focus on problems unique to their product**  
What kind of problems are unique? Expand on this, maybe use an example that people would be familiar with, perhaps from the "real" world.
- **maintain consistency for service users**  
Why is this important? What kind of consistency?   


- **working closely as a designer and developer in team of two.**   
Why is this working well? What's the traditional approach? What are the advantages from a developer and end user perspective?  
- **instead of designing in a separate applications like Sketch, we’re designing directly in the web browser**  
What impact does this have? Does it make it better for the end user or the consumer of the design system? What are the disadvantages? (_I would really like to read a looooong post about this soon_)

- **save time by not having to recreate designs**  
What does this mean? Expand.
- **balance user experience with code complexity**  
What does this mean? Can you give an example?
- **create a common language between designers and developers**  
Why is this valuable? What kind of language? Can you give an example?

- **find solutions to common problems**
What kind of problems? Would it make sense to specify that this is about designing common usage patterns / components?
- **improve based on feedback (including from children and young people)**  
How is this done? Can I participate? Is the GitHub repo open? Can I provide feedback there?
- **share our progress**
Where is it shared? If I'm interested, how can I keep up? 

By expanding each of the condensed thoughts a little you'll allow people a much more direct path to understanding your thoughts and the (excellent) narrative. There's absolutely no harm in repeating some of the things mentioned here later in specific posts, so don't worry about cannibalising future content. I think aiming for another 150-200 words per section we'll have something that reads like a satisfying post, and not just a teaser for future articles.

What do you think?

**Comment by kelliedesigner** [comment]
This issue is being closed as the acceptance criteria is fulfilled, and a follow-up issue will be created to action the feedback
