### ISSUE TITLE
[1 day] Investigate HTML to Sketch tooling

### ISSUE THREAD

**Issue by kelliedesigner** [barnardos/design-system#415]
AS a Designer who does not have coding experience
I WANT to be able to use tools I am comfortable with to produce high fidelity designs
SO that I can problem solve journeys and use the designs to:
- communicate ideas to stakeholders
- test with users

Creating separate Sketch artifacts of the Design System is unsustainable to manage at scale. 

However, it is is not a satisfactory solution to expect all designers to be in a position to pair, or to hand draw solutions.

This ticket is to investigate a method of using the Design System as the single source of truth of which Sketch files can be generated for a short-term need and then discarded.

https://github.com/brainly/html-sketchapp

**Comment by jeddy3** [comment]
The [HTML to Sketch](https://kimdal-hyeong.github.io/html-to-sketch-electron/download-analyst/) app seems to work remarkably well for this.

To import a component, make sure Sketch is open then:

1. Download the App
2. Right-click and select "Open", rather than double click
3. Select "Open" in the dialog box.
4. Type "https://design-system.barnardos.org.uk/" into the URL bar
5. Navigate to the page with the component on
6. Click the "Pick" button and select the component

The component should now appear in Sketch.
