### ISSUE TITLE
Fix color contrast of AttentionGrabbingLink

### ISSUE THREAD

**Issue by ritapatel7** [barnardos/design-system#73]
Does this colour contrast issue need to be fixed on this page?

![image](https://user-images.githubusercontent.com/35486145/37468373-c654b8f6-285a-11e8-9961-02a7d9d4c80f.png)

**Comment by kelliewellingtons** [comment]
When creating this component, we wanted to maximise the vibrancy of the colours to maintain the Barnardo's brand.

Therefore we chose a contrast that was compliant for AA Large, rather than needed to move to darker shades in order to comply with AA Normal.

We made the deliberate call to the typeface to not be bold, knowing that it wouldn't strictly pass AA standard, in order to differentiate the AttentionGrabbingLink from the SubmitAction.

However this is a good point, that if we want to strictly adhere to AA standard, the best option may be to make the text bold so that it then complies with AA Large.
