### ISSUE TITLE
Fix communication of type scale

### ISSUE THREAD

**Issue by jeddy3** [barnardos/design-system#84]
A user of the service said it would be useful to have the lower end of the type scale written out, e.g:

<img width="454" alt="screen shot 2018-03-22 at 18 57 11" src="https://user-images.githubusercontent.com/808227/37792139-e5804eea-2e02-11e8-9452-56e21e0b7606.png">

**Comment by kelliewellingtons** [comment]
Key findings from [Torchbox](https://torchbox.com/blog/designing-beautiful-websites-typographic-scale/)

**The Problem - translating print-based typographic thinking to digital**
- The standard approach of creating flat Photoshop designs and developers having to translate psd’s, means things get lost in translation
- We moved to design in the browser a few years ago - so we can start off developing with good typographic foundations, and not reacting only when things break on the screen
- Unlike the world of print, the size and space that we digital designers have to work with is fluid
- While dramatic h1 titles look great on our desktops, on phones they become ridiculous and waste too much space
- We combat this with media-queries, but at Torchbox we’ve been keen to avoid this, as that is merely reacting to a problem instead of investing in a solid solution.
- Also this approach can become a nightmare on larger sites, resulting in compromised layouts, where the design suffers in the no-mans-land between break points. By adding more fixes, you just increase the number of font style and therefore the complexity of your project, leaving you with a stylesheet as unmaintainable as a house built on sand

**The solution - a typographic scale**
- The less space we have, the bigger things become - meaning the distance between competing elements becomes exaggerated. This is where design isn’t just about following rules - it’s about combating these optical illusions and returning balance and harmony. It’s important to scale fonts sizes, but in a way that can be easily maintained and adjusted

**It’s all about the baseline**
- Start mobile first and set a baseline font size, then begin to implement a sliding scale in the CSS, which works across all your breakpoints

![heading_1 width-1280](https://user-images.githubusercontent.com/6122118/38924549-2d9c7710-42f5-11e8-9279-ac564e58c3ab.png)
